{

   "data_path": "/p/project/hai_verite/training_repository/data/merged/les_faits",
   
   
   "vocab-file": "/p/project/hai_verite/training_repository/artefacts/tokenizer/gpt-verite_tokenizer.json",
   "tokenizer_type": "HFTokenizer",

   "pipe-parallel-size": 0,
   "model-parallel-size": 1,


   "train_micro_batch_size_per_gpu": 24,
   "gradient_accumulation_steps": 12,
   "data-impl": "mmap",
   "split": "1000,0,0",


   "num-layers": 38,
   "hidden-size": 512,
   "num-attention-heads": 16,
   "seq-length": 2048,
   "max-position-embeddings": 2048,
   "pos-emb": "rotary",
   "rotary-pct": 0.25,
   "no-weight-tying": true,
   "gpt-j-residual": true,
   "output-layer-parallelism": "column",

   #"attention_config": [[["flash"], 24]],
   "scaled_upper_triang_masked_softmax_fusion": true,
   "bias_gelu_fusion": true,
   
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.006,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8
     }
   },
   "min_lr": 0.0006,

   "init_method": "normal",
   "output_layer_init_method": "scaled_normal",
   "init_method_std": 0.02,



   "use-mup": true,
   "save-base-shapes": false,   # this only needs to be enabled once in order to generate the base-shapes-file on each rank
   "base-shapes-file": "/p/project/hai_verite/training_repository/gpt-verite_/configs/gpt-verite/proxy_shape/", # # load base shapes from this file
   "coord-check": false, # generate coord check plots to verify mup's implementation in neox

   "mup-init-scale": 1.0,
   "mup-attn-temp": 1.0,
   "mup-output-temp": 1.0,
   "mup-embedding-mult": 1.0,
   "mup-rp-embedding-mult": 1.0,

   "zero_optimization": {
    "stage": 2,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true
  },

   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0.0,
   "attention-dropout": 0.0,

   # precision settings
   "precision": "bfloat16",

   "fp32_allreduce": true,

   "train-iters": 21834,
   "lr-decay-iters": 21834,
   "distributed-backend": "nccl",
   "lr-decay-style": "linear",
   "warmup": 0.02,
   "checkpoint-factor": 2000,
   "eval-interval": 1000,
   "eval-iters": 10,
   "log-interval": 1,
   "steps_per_print": 1,

   "use_wandb": false,
   "wandb_project": "GPT-Verite",
   "wandb_group": "MUP_Standard",

   "keep-last-n-checkpoints": 4,
   "wall_clock_breakdown": true,

   "exit_interval": 1500
}
